#!/bin/zsh
# ~/.zprofile
# Last Modified: 12/05/2013 04:26 AM ICT

if [ -f ~/.zshrc ]; then
       source ~/.zshrc
fi

### START-Keychain ###
# Let re-use ssh-agent and/or gpg-agent between logins
keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### END-Keychain ###

# End of ~/.zprofile