#!/bin/bash
# ~/.bash_profile
# Last Modified: Wed 06 Feb 2013 10:31:24 AM ICT

if [ -f ~/.bashrc ]; then
       source ~/.bashrc
fi

### START-Keychain ###
# Let re-use ssh-agent and/or gpg-agent between logins
keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### END-Keychain ###

# End of ~/.bash_profile